from human_status import HumanStatus

BG_COLOR = "#ffffff"

HUMAN_SIZE_RADIUS = 5
HUMAN_CHANGE_VELOCITY_PROBABILITY = 0.05
HUMAN_MAX_VELOCITY = 2

HUMAN_STATUS_COLOR = {HumanStatus.SICK: "#ff0000",
                      HumanStatus.HEALTHY: "#00ff00",
                      HumanStatus.CONTAGIOUS: "#fa886b",
                      HumanStatus.RECOVERED: "#e5f7b2"}

HUMAN_COUNT = 200
HUMAN_STATIONARY_PROBABILITY = 0.60
HUMAN_SICK_PROBABILITY = 0.20

CONTAGIOUS_TIME = 60
SICK_TIME = 60

INFECTION_DISTANCE = 2 * HUMAN_SIZE_RADIUS + 5
